"""Create the IISE staffing trade-off figure from audited by-date outputs."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from statistics import fmean, stdev

import matplotlib as mpl
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[1]

LABELS = {
    "robust_endogenous": "Robust endogenous",
    "nominal_value": "Nominal-value criterion",
    "fixed_two_teams": "Fixed two teams",
}
COLORS = {
    "robust_endogenous": "#2474B5",
    "nominal_value": "#D17A22",
    "fixed_two_teams": "#6B7280",
}
MARKERS = {
    "robust_endogenous": "o",
    "nominal_value": "s",
    "fixed_two_teams": "^",
}


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def stats(rows: list[dict[str, str]], metric: str):
    grouped: dict[tuple[str, float], list[float]] = defaultdict(list)
    for row in rows:
        grouped[(row["policy"], float(row["team_cost"]))].append(float(row[metric]))
    out = {}
    for key, values in grouped.items():
        out[key] = (fmean(values), stdev(values) if len(values) > 1 else 0.0)
    return out


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=ROOT / "outputs" / "iise_staffing_policy_by_date.csv",
        help="By-date staffing-policy CSV generated by summarize_iise_staffing.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "figures",
        help="Directory for PDF, SVG, TIFF, and PNG figure files.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = read_rows(args.input)
    team_stats = stats(rows, "selected_teams")
    value_stats = stats(rows, "net_robust_value")
    costs = sorted({float(row["team_cost"]) for row in rows})

    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "font.size": 8,
            "axes.labelsize": 8.5,
            "axes.titlesize": 9,
            "axes.linewidth": 0.8,
            "xtick.labelsize": 7.5,
            "ytick.labelsize": 7.5,
            "legend.fontsize": 7.3,
            "legend.frameon": False,
            "pdf.fonttype": 42,
            "svg.fonttype": "none",
        }
    )

    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.0), constrained_layout=True)
    for ax in axes:
        ax.spines[["top", "right"]].set_visible(False)
        ax.grid(axis="y", color="#D9DEE5", linewidth=0.55, alpha=0.8)
        ax.set_axisbelow(True)
        ax.set_xticks(costs)
        ax.set_xlabel("Normalized cost per team")

    for policy in LABELS:
        means = [team_stats[(policy, cost)][0] for cost in costs]
        sds = [team_stats[(policy, cost)][1] for cost in costs]
        axes[0].plot(
            costs,
            means,
            color=COLORS[policy],
            marker=MARKERS[policy],
            markersize=4.2,
            linewidth=1.5,
            label=LABELS[policy],
        )
        if policy != "fixed_two_teams":
            axes[0].fill_between(
                costs,
                [m - s for m, s in zip(means, sds)],
                [m + s for m, s in zip(means, sds)],
                color=COLORS[policy],
                alpha=0.10,
                linewidth=0,
            )

        value_means = [value_stats[(policy, cost)][0] for cost in costs]
        axes[1].plot(
            costs,
            value_means,
            color=COLORS[policy],
            marker=MARKERS[policy],
            markersize=4.2,
            linewidth=1.5,
            label=LABELS[policy],
        )

    axes[0].set_ylabel("Selected field teams")
    axes[0].set_ylim(0.8, 5.2)
    axes[0].set_title("a  Capacity response", loc="left", fontweight="bold")
    axes[1].set_ylabel("Worst-case net value")
    axes[1].set_title("b  Protected value after staffing cost", loc="left", fontweight="bold")
    axes[1].axhline(0, color="#9CA3AF", linewidth=0.7, linestyle="--")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", bbox_to_anchor=(0.5, 1.04), ncol=3)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    stem = args.output_dir / "fig_iise_staffing_tradeoff"
    fig.savefig(stem.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(stem.with_suffix(".svg"), bbox_inches="tight")
    fig.savefig(stem.with_suffix(".tiff"), dpi=600, bbox_inches="tight")
    fig.savefig(stem.with_suffix(".png"), dpi=220, bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    main()
